FROM python:3.11-slim

WORKDIR /app

COPY UI/requirements.txt .

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONPATH=/app

EXPOSE 7860

CMD ["python", "UI/gradio_ui.py"]